# Generated by Django 4.0.5 on 2024-11-22 23:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(error_messages={'unique': 'Esta categoria ya está registrada'}, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='', max_length=500)),
                ('nombre_quien_recibe', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('direccion_entrega', models.TextField(default='', max_length=300)),
                ('estado', models.IntegerField(choices=[[0, 'empacando'], [1, 'esperando viaje'], [2, 'enviado'], [3, 'entregado'], [4, 'cancelado']], default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estim', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id_orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(error_messages={'unique': 'Este SKU ya está registrado'}, max_length=10, unique=True)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('descripcion', django_quill.fields.QuillField(blank=True, default='sin descripcion')),
                ('Precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('precio_oferta', models.IntegerField(blank=True)),
                ('stock', models.IntegerField()),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.marca')),
            ],
            options={
                'ordering': ['id_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(error_messages={'unique': 'Esta tipo de producto ya está registrado'}, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('RUT', models.CharField(blank=True, default='', error_messages={'unique': 'El rut ya está registrado.'}, max_length=13, unique=True)),
                ('nacimiento', models.DateField(null=True)),
                ('genero', models.IntegerField(choices=[[0, 'hombre'], [1, 'Mujer'], [2, 'sin especificar']], default=2)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('direccion', models.CharField(default='', max_length=300)),
                ('region', models.IntegerField(blank=True, choices=[[0, 'seleccione...'], [1, 'Arica y Parinacota'], [2, 'Tarapacá'], [3, 'Antofagasta'], [4, 'Atacama'], [5, 'Coquimbo'], [6, 'Valparaíso'], [7, 'Región Metropolitana de Santiago'], [8, "Región del Libertador General Bernardo O'Higgins"], [9, 'Región del Maule'], [10, 'Región de Ñuble'], [11, 'Región del Biobío'], [12, 'Región de La Araucanía'], [13, 'Región de Los Ríos'], [14, 'Región de Los Lagos'], [15, 'Región de Aysén del General Carlos Ibáñez del Campo'], [16, 'Región de Magallanes y de la Antártica Chilena']], null=True)),
                ('comuna', models.IntegerField(blank=True, choices=[[1, 'Cerrillos'], [2, 'Cerro Navia'], [3, 'Conchalí'], [4, 'El Bosque'], [5, 'Estación Central'], [6, 'Huechuraba'], [7, 'Independencia'], [8, 'La Cisterna'], [9, 'La Florida'], [10, 'La Granja'], [11, 'La Pintana'], [12, 'La Reina'], [13, 'Las Condes'], [14, 'Lo Barnechea'], [15, 'Lo Espejo'], [16, 'Lo Prado'], [17, 'Macul'], [18, 'Maipú'], [19, 'Ñuñoa'], [20, 'Pedro Aguirre Cerda'], [21, 'Peñalolén'], [22, 'Providencia'], [23, 'Pudahuel'], [24, 'Quilicura'], [25, 'Quinta Normal'], [26, 'Recoleta'], [27, 'Renca'], [28, 'San Joaquín'], [29, 'San Miguel'], [30, 'San Ramón'], [31, 'Santiago Centro'], [32, 'Vitacura'], [33, 'Puente Alto'], [34, 'San Bernardo'], [35, 'Pirque'], [36, 'San José de Maipo'], [37, 'Colina'], [38, 'Lampa'], [39, 'Tiltil'], [40, 'Buin'], [41, 'Calera de Tango'], [42, 'Paine'], [43, 'Melipilla'], [44, 'Curacaví'], [45, 'María Pinto'], [46, 'San Pedro'], [47, 'Talagante'], [48, 'El Monte'], [49, 'Isla de Maipo'], [50, 'Padre Hurtado'], [51, 'Peñaflor']], null=True)),
                ('foto_de_Usuario', models.ImageField(null=True, upload_to='usuarios')),
                ('es_profesor', models.BooleanField(default=False)),
                ('es_admin_biblioteca', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('desc_valoracion', django_quill.fields.QuillField()),
                ('producto_valorado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.producto')),
                ('usuario_validacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_valoracion'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(error_messages={'unique': 'Esta subcategoria ya está registrada'}, max_length=30, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcat_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.tipoproducto'),
        ),
        migrations.CreateModel(
            name='Ordenxproducto',
            fields=[
                ('id_ordenxproducto', models.AutoField(primary_key=True, serialize=False)),
                ('valorado', models.BooleanField(default=False)),
                ('cantidad_estrellas', models.IntegerField(default=0)),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('id_orden_relacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.producto')),
            ],
            options={
                'ordering': ['-id_ordenxproducto'],
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MensajeOrden',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_mensaje', models.TextField(max_length=40)),
                ('contenido_mensaje', django_quill.fields.QuillField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_orden_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.orden')),
                ('id_usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_mensaje'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.tipoproducto'),
        ),
    ]
