# Generated by Django 4.0.5 on 2024-11-22 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.TextField(max_length=30)),
                ('desc_asignatura', django_quill.fields.QuillField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField()),
                ('duracion', models.IntegerField(blank=True, help_text='Duración en semanas', null=True)),
                ('cupos_maximos', models.PositiveIntegerField(default=30)),
                ('horario', models.TextField(blank=True, null=True)),
                ('imagen_asignatura', models.ImageField(upload_to='asignaturas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaXAlumno',
            fields=[
                ('id_asignaturaxalmnos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('promedio_notas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_inscripcion', models.CharField(choices=[('inscrito', 'Inscrito'), ('en curso', 'En curso'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='inscrito', max_length=20)),
                ('id_alumno_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_asignatura_rel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id_tipo_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_membresia', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadClase',
            fields=[
                ('id_unidad_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.TextField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_orden', models.PositiveIntegerField(default=1)),
                ('imagenclase', models.ImageField(upload_to='unidades')),
                ('materia_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('activa', models.BooleanField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('tipo_membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.tipomembresia')),
                ('usuario_asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_membresia'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=1)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=1.0, help_text='Ponderación de la nota', max_digits=4)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('asignatura_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.asignaturaxalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoClase',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_contenido', models.TextField(max_length=60)),
                ('subtitulo_contenido', models.TextField(max_length=150)),
                ('contenido_clases', django_quill.fields.QuillField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('unidad_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.unidadclase')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contenido', models.TextField(max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_clase', models.DateField()),
                ('inicio_clase', models.TimeField()),
                ('final_clase', models.TimeField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_clases/')),
                ('invitacion_zoom_link', models.TextField(max_length=500)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('confirmacion', models.BooleanField()),
                ('motivo_ausencia', models.TextField(blank=True, null=True)),
                ('fecha_asistencia', models.DateTimeField(auto_now_add=True)),
                ('asignatura_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.asignaturaxalumno')),
                ('clase_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Classes.clase')),
            ],
            options={
                'unique_together': {('clase_asistencia', 'asignatura_alumno')},
            },
        ),
    ]
